version: '2.4'

services:
        meshcentral2: 
                image: "jamesits/meshcentral2:latest"
                build: "."
                restart: "unless-stopped"
                ulimits:
                        nofile:
                                soft: 800000
                                hard: 1000000
                volumes:
                        - "./deploy/meshcentral-data:/srv/meshcentral2/meshcentral-data"
                        - "./deploy/meshcentral-files:/srv/meshcentral2/meshcentral-files"
                ports: 
                        - "80:80"
                        - "443:443"
                        - "4433:4433"
        mongo:
                image: "mongo:4"
                command: "--serviceExecutor adaptive"
                restart: "unless-stopped"
                volumes:
                        - "./deploy/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
                        - "./deploy/mongodb-data:/data/db"
                        - "./deploy/mongodb-config:/data/configdb"
                environment:
                        - "MONGO_INITDB_DATABASE=meshcentral"
                        - "MONGO_NON_ROOT_USERNAME=meshcentral"
                        - "MONGO_NON_ROOT_PASSWORD=hunter2"
                        - "MONGO_INITDB_ROOT_USERNAME=root"
                        - "MONGO_INITDB_ROOT_PASSWORD=hunter2"

